name: 'Create Changesets Snapshots'
description:
  'Publishes snapshot releases for package versions updated by changeset files,
  intended for use in PR workflows. '

branding:
  icon: 'camera'
  color: 'green'

runs:
  using: node20
  main: dist/index.js
